---

_You are currently looking at **version 1.0** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-text-mining/resources/d9pwm) course resource._

---

# Assignment 1

In this assignment, you'll be working with messy medical data and using regex to extract relevant infromation from the data. 

Each line of the `dates.txt` file corresponds to a medical note. Each note has a date that needs to be extracted, but each date is encoded in one of many formats.

The goal of this assignment is to correctly identify all of the different date variants encoded in this dataset and to properly normalize and sort the dates. 

Here is a list of some of the variants you might encounter in this dataset:
* 04/20/2009; 04/20/09; 4/20/09; 4/3/09
* Mar-20-2009; Mar 20, 2009; March 20, 2009;  Mar. 20, 2009; Mar 20 2009;
* 20 Mar 2009; 20 March 2009; 20 Mar. 2009; 20 March, 2009
* Mar 20th, 2009; Mar 21st, 2009; Mar 22nd, 2009
* Feb 2009; Sep 2009; Oct 2010
* 6/2008; 12/2009
* 2009; 2010

Once you have extracted these date patterns from the text, the next step is to sort them in ascending chronological order accoring to the following rules:
* Assume all dates in xx/xx/xx format are mm/dd/yy
* Assume all dates where year is encoded in only two digits are years from the 1900's (e.g. 1/5/89 is January 5th, 1989)
* If the day is missing (e.g. 9/2009), assume it is the first day of the month (e.g. September 1, 2009).
* If the month is missing (e.g. 2010), assume it is the first of January of that year (e.g. January 1, 2010).

With these rules in mind, find the correct date in each note and return a pandas Series in chronological order of the original Series' indices.

For example if the original series was this:

    0    1999
    1    2010
    2    1978
    3    2015
    4    1985

Your function should return this:

    0    2
    1    4
    2    0
    3    1
    4    3

Your score will be calculated using [Kendall's tau](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient), a correlation measure for ordinal data.

*This function should return a Series of length 500 and dtype int.*

In [1]:
import os
os.getcwd()

'C:\\Users\\S.Sagara\\Documents\\Data Science\\coursera\\Applied Data Science with Python Specialization\\Applied Text Mining'

In [2]:
import pandas as pd

doc = []
with open('dates.txt') as file:
    for line in file:
        doc.append(line)

df = pd.Series(doc)
df.head(10)

0         03/25/93 Total time of visit (in minutes):\n
1                       6/18/85 Primary Care Doctor:\n
2    sshe plans to move as of 7/8/71 In-Home Servic...
3                7 on 9/27/75 Audit C Score Current:\n
4    2/6/96 sleep studyPain Treatment Pain Level (N...
5                    .Per 7/06/79 Movement D/O note:\n
6    4, 5/18/78 Patient's thoughts about current su...
7    10/24/89 CPT Code: 90801 - Psychiatric Diagnos...
8                         3/7/86 SOS-10 Total Score:\n
9             (4/10/71)Score-1Audit C Score Current:\n
dtype: object

In [3]:
def date_sorter():
    
    # Your code here
    
    return # Your answer here

In [148]:
#make dataframe
df3 = pd.DataFrame(columns=['text'])
df3['text'] = df

In [149]:
#dates ver1 standard format date extraction
df3['dates'] = df.str.findall(r'\d{1,2}[/-]\d{1,2}[/-]\d{2,4}')

In [150]:
#dates ver 2 4-digits, only year is available
df3['dates2'] = df.str.findall(r'[12]\d{3}')

In [151]:
#dates ver 3 Month is like Oct, October
df3['dates3'] = df.str.findall(r'(?:\d{1,2} )?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,]* (?:\d{1,2}, )?\d{4}')

In [152]:
#dates ver 4 Month is like Oct, October but no comma after dates
df3['dates4'] = df.str.findall(r'(?:\d{1,2} )?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,]* (?:\d{1,2} )?\d{4}')

In [153]:
#dates ver 5 like "6/1998"
df3['dates5'] = df.str.findall(r'\d{1,2}[/-]\d{2,4}')

In [73]:
#year treatment
rown = []
year = []
for i in df3['dates']:
    if len(i) == 0:
        rn = 0
        yr = 0
    else:
        rn = 1
        yr = pd.to_datetime(i[0]).year
    rown.append(rn)
    year.append(yr)

In [238]:
#add year 1 and month 1
year1 = []
month1 = []
for i in df3['dates']:
    if len(i) == 0:
        rn = 0
        yr = 0
        mth = 0
    else:
        yr = pd.to_datetime(i[0]).year
        mth = pd.to_datetime(i[0]).month
    year1.append(yr)
    month1.append(mth)
df3['year1'] = year1
df3['month1'] = month1

In [166]:
#add year 2, no month because dates2 is only yearly
year2 = []
for i in df3['dates2']:
    if len(i) == 0:
        rn = 0
        yr = 0
    else:
        yr = pd.to_datetime(i[0]).year
    year2.append(yr)
#year2
df3['year2'] = year2

In [217]:
#for year 3 fix misspell
for i in range(298,300):
    df3['dates3'][i] = np.where(df3['dates3'][i] == ['Janaury 1993'], ['January 1993'], df3['dates3'][i])
    df3['dates4'][i] = np.where(df3['dates4'][i] == ['Janaury 1993'], ['January 1993'], df3['dates4'][i])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [218]:
#for year 3 fix misspell 2
for i in range(310,315):
    df3['dates3'][i] = np.where(df3['dates3'][i] == ['Decemeber 1978'], ['December 1978'], df3['dates3'][i])
    df3['dates4'][i] = np.where(df3['dates4'][i] == ['Decemeber 1978'], ['December 1978'], df3['dates4'][i])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [244]:
#add year 3 and month 3
year3 = []
month3 = []
for i in df3['dates3']:
    if len(i) == 0:
        rn = 0
        yr = 0
        mth = 0
    else:
        yr = pd.to_datetime(i[0]).year
        mth = pd.to_datetime(i[0]).month
    year3.append(yr)
    month3.append(mth)
#month3
df3['year3'] = year3
df3['month3'] = month3

In [247]:
#add year 4 and month 4
year4 = []
month4 = []
for i in df3['dates4']:
    if len(i) == 0:
        rn = 0
        yr = 0
        mth = 0
    else:
        yr = pd.to_datetime(i[0]).year
        mth = pd.to_datetime(i[0]).month
    year4.append(yr)
    month4.append(mth)
df3['year4'] = year4
df3['month4'] = month4

In [266]:
for i in range(400,410):
    df3['dates5'][i] = np.where(df3['dates5'][i] == ['12/2014', '5-10'], ['12/2014'], df3['dates5'][i])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [304]:
#add year 5 - in fact year no need coz year2 covers it
month5 = []
for i in range(0,343):
    mth = 0
    month5.append(mth)
for i in range(343,500):
    mth = pd.to_datetime(df3['dates5'][i]).month
    month5.append(mth)
df3['month5'] = month5

In [232]:
df3['yearfin'] = np.where(df3['year1'] == 0, df3['year2'], df3['year1'])

In [305]:
df3

text         dates  dates2  \
0         03/25/93 Total time of visit (in minutes):\n    [03/25/93]      []   
1                       6/18/85 Primary Care Doctor:\n     [6/18/85]      []   
2    sshe plans to move as of 7/8/71 In-Home Servic...      [7/8/71]      []   
3                7 on 9/27/75 Audit C Score Current:\n     [9/27/75]      []   
4    2/6/96 sleep studyPain Treatment Pain Level (N...      [2/6/96]      []   
5                    .Per 7/06/79 Movement D/O note:\n     [7/06/79]      []   
6    4, 5/18/78 Patient's thoughts about current su...     [5/18/78]      []   
7    10/24/89 CPT Code: 90801 - Psychiatric Diagnos...    [10/24/89]      []   
8                         3/7/86 SOS-10 Total Score:\n      [3/7/86]      []   
9             (4/10/71)Score-1Audit C Score Current:\n     [4/10/71]      []   
10   (5/11/85) Crt-1.96, BUN-26; AST/ALT-16/22; WBC...     [5/11/85]      []   
11                       4/09/75 SOS-10 Total Score:\n     [4/09/75]      []   
12   8/01/98 Communication with referring physician...     [8/01/98]      []   
13   1/26/72 Communication with referring physician...     [1/26/72]      []   
14   5/24/1990 CPT Code: 90792: With medical servic...   [5/24/1990]  [1990]   
15   1/25/2011 CPT Code: 90792: With medical servic...   [1/25/2011]  [2011]   
16         4/12/82 Total time of visit (in minutes):\n     [4/12/82]      []   
17        1; 10/13/1976 Audit C Score, Highest/Date:\n  [10/13/1976]  [1976]   
18                 4, 4/24/98 Relevant Drug History:\n     [4/24/98]      []   
19   ) 59 yo unemployed w referred by Urgent Care f...     [5/21/77]      []   
20         7/21/98 Total time of visit (in minutes):\n     [7/21/98]      []   
21                     210/21/79 SOS-10 Total Score:\n    [10/21/79]      []   
22    3/03/90 CPT Code: 90792: With medical services\n     [3/03/90]      []   
23    2/11/76 CPT Code: 90792: With medical services\n     [2/11/76]      []   
24   07/25/1984 CPT Code: 90791: No medical services\n  [07/25/1984]  [1984]   
25   4-13-82 Other Child Mental Health Outcomes Sca...     [4-13-82]      []   
26    9/22/89 CPT Code: 90792: With medical services\n     [9/22/89]      []   
27      9/02/76 CPT Code: 90791: No medical services\n     [9/02/76]      []   
28                              9/12/71 [report_end]\n     [9/12/71]      []   
29   10/24/86 Communication with referring physicia...    [10/24/86]      []   
..                                                 ...           ...     ...   
470  y1983 Clinic Hospital, first hospitalization, ...            []  [1983]   
471  tProblems Urinary incontinence : mild urge inc...            []  [1999]   
472  .2010 - wife; nightmares and angry outbursts; ...            []  [2010]   
473       shx of TBI (1975) ISO MVA.Medical History:\n            []  [1975]   
474  sPatient reported losing three friends that pa...            []  [1972]   
475                      TSH okay in 2015 Prior EKG:\n            []  [2015]   
476  1989 Family Psych History: Family History of S...            []  [1989]   
477  oEnjoys animals, had a dog x 14 yrs who died i...            []  [1994]   
478  eHistory of small right parietal subgaleal hem...            []  [1993]   
479  sIn KEP Psychiatryfor therapy and medications ...            []  [1996]   
480  1. Esophageal cancer, dx: 2013, on FOLFOX with...            []  [2013]   
481                                      y1974 (all)\n            []  [1974]   
482  h/o restraining order by sister/mother in 1990...            []  [1990]   
483  sTexas Medical Center; Oklahoma for 2 weeks; 1...            []  [1995]   
484  Death of former partner in 2004 by overdose as...            []  [2004]   
485  Was "average" student.  "I didn't have too man...            []  [1987]   
486  Contemplating jumping off building - 1973 - di...            []  [1973]   
487  appendectomy s/p delivery 1992 Prior relevant ...            []  [1992]   
488  tProblems renal cell cancer : s/p nephrectomy

In [288]:
df3.iloc[342:500]

text dates  dates2  \
342  5Bethania Hospital March 1976 Hx of Outpatient...    []  [1976]   
343                      6/1998 Primary Care Doctor:\n    []  [1998]   
344  s 52 y/o MWM h/o chronic depression, anxiety, ...    []  [2005]   
345                  10/1973 Hx of Brain Injury: Yes\n    []  [1973]   
346                      9/2005 Primary Care Doctor:\n    []  [2005]   
347  s 03/1980 Positive PPD: treated with INH for 6...    []  [1980]   
348  12/2005 Family Psych History: Family History o...    []  [2005]   
349                      5/1987 Primary Care Doctor:\n    []  [1987]   
350                      5/2004 Primary Care Doctor:\n    []  [2004]   
351  A pleasant 28 yo woman with no formal psychiat...    []  [1974]   
352  See initial PROMPTCARE evaluation from 3/1986 ...    []  [1986]   
353                     10/1997 Primary Care Doctor:\n    []  [1997]   
354  Deviated septum, 3/1993 Activities of Daily Li...    []  [1993]   
355                      3/1981 Primary Care Doctor:\n    []  [1981]   
356  . Patient states that she will follow up with ...    []  [2003]   
357                         % 10/1993 Echo: LVEF 60%\n    []  [1993]   
358                            .Mother died, 1/1983.\n    []  [1983]   
359                                  . GBSG : 7/1994\n    []  [1994]   
360                     12/2008 Primary Care Doctor:\n    []  [2008]   
361  n Abnormal CXR : 10/1980 ? scarring @ R heart ...    []  [1980]   
362  md. metabolic montioring as indicated inc. ann...    []  [2003]   
363                     12/1975 Primary Care Doctor:\n    []  [1975]   
364  sDr. Yaeger at Jarman Memorial Hospital for me...    []  [2010]   
365  sCurrently See Jeremiah Ngo in Omak. Sees 2x m...    []  [1997]   
366  1. Metastatic pancreatic adenocarcinoma, dx: 7...    []  [2014]   
367  rtherapy: Patient states that she will follow ...    []  [2001]   
368           craniotomy 8/1986 Prior relevant labs:\n    []  [1986]   
369                      1/1978 Primary Care Doctor:\n    []  [1978]   
370  4 (9/1975)Patient's thoughts about current sub...    []  [1975]   
371  s Pt is a 73-y.o. MWW with a history of recurr...    []  [2009]   
..                                                 ...   ...     ...   
470  y1983 Clinic Hospital, first hospitalization, ...    []  [1983]   
471  tProblems Urinary incontinence : mild urge inc...    []  [1999]   
472  .2010 - wife; nightmares and angry outbursts; ...    []  [2010]   
473       shx of TBI (1975) ISO MVA.Medical History:\n    []  [1975]   
474  sPatient reported losing three friends that pa...    []  [1972]   
475                      TSH okay in 2015 Prior EKG:\n    []  [2015]   
476  1989 Family Psych History: Family History of S...    []  [1989]   
477  oEnjoys animals, had a dog x 14 yrs who died i...    []  [1994]   
478  eHistory of small right parietal subgaleal hem...    []  [1993]   
479  sIn KEP Psychiatryfor therapy and medications ...    []  [1996]   
480  1. Esophageal cancer, dx: 2013, on FOLFOX with...    []  [2013]   
481                                      y1974 (all)\n    []  [1974]   
482  h/o restraining order by sister/mother in 1990...    []  [1990]   
483  sTexas Medical Center; Oklahoma for 2 weeks; 1...    []  [1995]   
484  Death of former partner in 2004 by overdose as...    []  [2004]   
485  Was "average" student.  "I didn't have too man...    []  [1987]   
486  Contemplating jumping off building - 1973 - di...    []  [1973]   
487  appendectomy s/p delivery 1992 Prior relevant ...    []  [1992]   
488  tProblems renal cell cancer : s/p nephrectomy ...    []  [1977]   
489      ran own business for 35 years, sold in 1985\n    []  [1985]   
490                                Lab: B12 969 2007\n    []  [2007]   
491                                 )and 8mo in 2009\n    []  [2009]   
492  .Moved to USA in 1986. Suffered from malnutrit...    []  [1986]   
493                                            r1978\n    []  [1978]   
494  . Went to Eme

In [271]:
for i in range(300,310):
    print(pd.to_datetime(df3['dates5'][i]).year)

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]


In [235]:
df3.to_csv("df3.csv")

In [12]:
from datetime import datetime

In [117]:
import numpy as np

In [118]:
df3['year'] = np.where(df3['flg1'] == 0, df3['dates2'], df3['dates'])

In [146]:
year1 = []
for i in df3['dates5'][410:420]:
    yr = pd.to_datetime(i).year
    year1.append(yr)
year1

[array([2007]),
 array([2010]),
 array([1990]),
 array([2016]),
 array([2004]),
 array([1973]),
 array([1987]),
 array([2000]),
 array([1975]),
 array([1977])]

In [143]:
df3.iloc[410:430]

text dates  dates2 dates3  \
410  . Patient primary concern is related to a TBI ...    []  [2007]     []   
411  8/2010 QTc 433 ms.Pertinent Medical Review of ...    []  [2010]     []   
412  kNotice that in 03/1990, sustained a bizarre i...    []  [1990]     []   
413                     11/2016 Primary Care Doctor:\n    []  [2016]     []   
414        n4/2004 R mastectomy with reconstruction.\n    []  [2004]     []   
415                      2/1973 Primary Care Doctor:\n    []  [1973]     []   
416  s1 CSU stay at Donelson Hospital 7/1987 in the...    []  [1987]     []   
417  tHead trauma-8/2000;s/p traumatic brain injury...    []  [2000]     []   
418  ANTIDEPRESSANT TREATMENT HISTORY  per Dr. Bear...    []  [1975]     []   
419  TSH in 5/1977 okayPertinent Medical Review of ...    []  [1977]     []   
420  .Patient reports overall stable mental health ...    []  [2000]     []   
421  sChesterfield 9/1984 for 3 weeks for dual diag...    []  [1984]     []   
422                      4/1973 Primary Care Doctor:\n    []  [1973]     []   
423  Polyarteritis nodosa, presumed (p/w LE claudic...    []  [1986]     []   
424  db. routine metabolic montoring as indicated a...    []  [1979]     []   
425  sS/P TAH/BSO : 7/2004 for endometrial hyperpla...    []  [2004]     []   
426  Retired in 11/1984 after teaching for 30 years...    []  [1984]     []   
427  6e. monitor pt's depressive experience in cont...    []  [2016]     []   
428                      e12/2007 dx of endocarditis\n    []  [2007]     []   
429                     11/1982 Primary Care Doctor:\n    []  [1982]     []   

     flg1    year dates4     dates5  
410     0  [2007]     []  [01/2007]  
411     0  [2010]     []   [8/2010]  
412     0  [1990]     []  [03/1990]  
413     0  [2016]     []  [11/2016]  
414     0  [2004]     []   [4/2004]  
415     0  [1973]     []   [2/1973]  
416     0  [1987]     []   [7/1987]  
417     0  [2000]     []   [8/2000]  
418     0  [1975]     []   [8/1975]  
419     0  [1977]     []   [5/1977]  
420     0  [2000]     []   [3/2000]  
421     0  [1984]     []   [9/1984]  
422     0  [1973]     []   [4/1973]  
423     0  [1986]     []  [12/1986]  
424     0  [1979]     []   [4/1979]  
425     0  [2004]     []   [7/2004]  
426     0  [1984]     []  [11/1984]  
427     0  [2016]     []   [5/2016]  
428     0  [2007]     []  [12/2007]  
429     0  [1982]     []  [11/1982]

In [136]:
pd.to_datetime('May/2017')

Timestamp('2017-05-01 00:00:00')